# Generated by Django 3.0.4 on 2020-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200315_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username1',
            field=models.CharField(default='mar', max_length=30, unique=True),
        ),
    ]
