# Generated by Django 3.0.4 on 2020-03-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_username1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=16, unique=True)),
                ('program', models.TextField()),
                ('bodovi', models.IntegerField()),
                ('sem_redovni', models.IntegerField()),
                ('sem_izvanredni', models.IntegerField()),
                ('izborni', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'predmeti',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='student', max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=64, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Upisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Predmeti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upisi',
            },
        ),
    ]
