# Generated by Django 3.0.4 on 2020-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200316_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=55, unique=True, verbose_name='email'),
        ),
    ]
