# Generated by Django 3.0.4 on 2020-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200408_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='status',
            field=models.CharField(default='nepolozen', max_length=64),
        ),
    ]
