# Generated by Django 3.0.4 on 2020-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200501_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='sem_izvanredni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predmeti',
            name='sem_redovni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
