# Generated by Django 3.0.4 on 2020-05-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200501_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='program',
            field=models.TextField(default=None),
        ),
    ]
